build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

platform:
  - x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "set PATH=%PATH%;%PYTHON%;%PYTHON%\\Scripts"

install:
  - "pip install ."

test_script:
  - ps: "pip freeze | findstr QtPy"
  - ps: "pip freeze | findstr PyQt5"
  - ps: "pip freeze | findstr QScintilla"
  - ps: "pip freeze | findstr json-config"
  - ps: "pip freeze | findstr Sphinx"