sudo: required
language: python
python:
  - "3.6"
  - "3.7"
os:
  - linux
sudo: false
git:
  depth: 3
branches:
  only:
  - /.*/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f857b3596353a9b70720
    on_success: change
    on_failure: always
    on_start: never
  email:
    only: master
    on_success: never
    on_failure: always
    on_start: never
install:
  - sudo apt-get update
  - pip install pipenv
  - pipenv install .[TESTS]
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pyrcc5 -o AlphaHooks/resources.py AlphaHooks/resources.qrc
script:
  - python setup.py tests
