language: python
python:
  - "3.5"
  - "3.6"
os:
  - linux
sudo: false
git:
  depth: 3
branches:
  only:
  - /.*/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f857b3596353a9b70720
    on_success: change
    on_failure: always
    on_start: never
  email:
    only: master
    on_success: never
    on_failure: always
    on_start: never
install:
  - pip install .
script:
  - pip freeze | grep PyQt5
  - pip freeze | grep QScintilla
  - pip freeze | grep Sphinx