language: python
python:
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
sudo: false
git:
  depth: 3
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f857b3596353a9b70720
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
install:
  - pip install .
script:
  - pip freeze | grep PyQt5
  - pip freeze | grep QScintilla
